CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(250)                                        NOT NULL,
    email VARCHAR(254) UNIQUE                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                  NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(2000)                                       NOT NULL,
    category_id        BIGINT,
    confirmed_requests BIGINT                                              NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    description        VARCHAR(7000)                                       NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    initiator_id       BIGINT                                              NOT NULL,
    lat                NUMERIC                                             NOT NULL,
    lon                NUMERIC                                             NOT NULL,
    is_paid            BOOLEAN                                             NOT NULL,
    participant_limit  INTEGER                                             NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN                                             NOT NULL,
    state              VARCHAR(20)                                         NOT NULL,
    title              VARCHAR(120)                                        NOT NULL,
    views              BIGINT                                              NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories (id),
    FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS event_dates ON events (event_date);
CREATE INDEX IF NOT EXISTS category_ids ON events (category_id);
CREATE INDEX IF NOT EXISTS paid ON events (is_paid);

CREATE TABLE IF NOT EXISTS participation_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event_id     BIGINT                                              NOT NULL,
    requester_id BIGINT                                              NOT NULL,
    created      TIMESTAMP                                           NOT NULL,
    status       VARCHAR                                             NOT NULL,
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (requester_id) REFERENCES users (id),
    UNIQUE (event_id, requester_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title            VARCHAR(50)                                         NOT NULL,
    pinned           BOOLEAN                                             NOT NULL,
    event_ids_string TEXT
);

CREATE TABLE IF NOT EXISTS comments
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text            VARCHAR(4095)                                       NOT NULL,
    event_id        BIGINT                                              NOT NULL,
    author_id       BIGINT                                              NOT NULL,
    created         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    last_updated_by BIGINT,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    FOREIGN KEY (event_id) REFERENCES events (id),
    FOREIGN KEY (author_id) REFERENCES users (id),
    FOREIGN KEY (last_updated_by) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS event_comments ON comments (event_id);
CREATE INDEX IF NOT EXISTS author_comments ON comments (author_id);
CREATE INDEX IF NOT EXISTS created_comments ON comments (created);