CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  VARCHAR(255)                                        NOT NULL,
    email VARCHAR(512) UNIQUE                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(50) UNIQUE                                  NOT NULL
);

CREATE TABLE "events"
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    annotation         VARCHAR(2000)                                       NOT NULL,
    category_id        BIGINT                                              NOT NULL,
    confirmed_requests BIGINT                                              NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    description        VARCHAR(7000)                                       NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    initiator_id       BIGINT                                              NOT NULL,
    lat                NUMERIC                                             NOT NULL,
    lon                NUMERIC                                             NOT NULL,
    is_paid            BOOLEAN                                             NOT NULL,
    participant_limit  INTEGER                                             NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE                         NOT NULL,
    request_moderation BOOLEAN                                             NOT NULL,
    state              VARCHAR(20)                                         NOT NULL,
    title              VARCHAR(120)                                        NOT NULL,
    views              BIGINT                                              NOT NULL,
    FOREIGN KEY (category_id) REFERENCES categories (id),
    FOREIGN KEY (initiator_id) REFERENCES users (id)
);