version: '3.1'
services:
  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=statsUser
      - POSTGRES_PASSWORD=statsUserPassword

  stats-server:
    build: stats-service
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=statsUser
      - POSTGRES_PASSWORD=statsUserPassword
      - DB_HOST=db
      - DB_PORT=5432
      - TZ=Etc/UTC
  #      - TZ=Europe/Moscow

  ewm-service:
    build: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=mainUser
      - POSTGRES_PASSWORD=mainUserPassword
      - DB_HOST=db
      - DB_PORT=5432
      - TZ=Etc/UTC

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db
    ports:
      - "1234:5432"
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=mainUser
      - POSTGRES_PASSWORD=mainUserPassword
